### ISSUE TITLE
关于eemd-lstm训练集

### ISSUE THREAD

**Issue by Jackeylove827** [Corezcy/EEMD-LSTM-DO-Prediction#10]
你好，我在lstm.py里可以将训练集的情况显示出来，请问如何在eemd-lstm.py里显示？另外我想知道您的pdf里的异常值筛选图是怎样呈现的？

**Comment by Corezcy** [comment]
> 我在lstm.py里可以将训练集的情况显示出来，请问如何在eemd-lstm.py里显示？

- 我在lstm.py里可以将训练集的情况显示出来，请问如何在eemd-lstm.py里显示？

eemd-lstm.py 也会进行相应的处理并展现数据，如果没有，把结果展现的代码复制过去就好了

- pdf里的异常值筛选图是怎样呈现的

使用孤立森林异常值检测算法检测的
