### ISSUE TITLE
如何提高预测的准确度呢？谢谢！

### ISSUE THREAD

**Issue by allen20200111** [Corezcy/EEMD-LSTM-DO-Prediction#2]
EEMD+LSTM预测，作者的做法是测试集一次性全部进行了EEMD分解，然后将分解的结果作为了标签，这样看效果确实不错，准确度高达90%以上。然而现实的场景是，测试集不可能一次性完全知道的，每次只知道一个新原始值，也就意味着每次预测都需EEMD分解一次，而这种目前来看，效果很差，有什么好的办法没有呢？谢谢！

**Comment by Corezcy** [comment]
1、每次只知道一个新原始值
首先你的值要满足固定的滑动窗口的数量，和模型训练的时候保持一致；其次，如果训练的时候EEMD分解得到10条子序列（9imf + 1余项），如果后续数值较少，分解达不到10条子序列，预测效果会大大下降。目前我的做法是把新加入的值和原来的值一起分解，一定要满足10条子序列，具体做法如下所示：
`eemd = EEMD()
    eemd.noise_seed(12345)
    imfs = eemd.eemd(DO.reshape(-1),None,9) 9imf + 1余项`

2、每次预测都需要EEMD分解一次
目前我的做法是的，比如我的数据集（训练集 + 测试集）长度3000，有新的值加入后，整体后移，去掉第一个值，加入新值。这里可以参考一下浙江大学的`Yu-Xi Wu, Qing-Biao Wu , Jia-Qi Zhu`的`Improved EEMD-based crude oil price forecasting using LSTM networks`，论文里面根绝每次分解imf数量不一样的问题，挑选出最具影响力的imf，这样应该可以少分解。

3、如何提高预测的准确度
改变模型结构、寻找最合适的滑动窗口、调参


希望对你有帮助！

**Comment by Corezcy** [comment]
[EEMD-LSTM-石油价格预测.pdf](https://github.com/Corezcy/EEMD-LSTM-DO-Prediction/files/4893824/EEMD-LSTM-.pdf)

**Comment by allen20200111** [comment]
十分感谢！
我测试了一下，以偏差10%作为阀值来作为预测值是否准确的标准的话，
(1) 测试集全部分解后，将分解后的值再聚合作为测试集标签，准确度是95%以上。
(2) 每预测一次，取测试集的一个新加入的值，新加入的值和原来的值一起归一化处理，一起进行EEMD分解，分解得到几个IMF，
     取IMF的最后回望窗口的值进行预测，将每个IMF预测的值进行累加，逆归一化处理，和测试集t+1时刻真实值比较，这种方式，准确度只有57%左右。

每次都进行EEMD分解没有问题，我的主要问题是为什么新加入的值和原始值进行分解之后再预测，预测的值就不准确了呢？

同时我发现，不进行预测，只是简单如下操作：
    时间序列的值进行归一化处理，然后IMF分解，分解后的值进行累加运算，逆归一化处理，此时得到的值与原始值进行比较，已经有约20%的值偏离了10%以上，这意味着如果将IMF的分解值作为标签时，哪怕每个IMF预测的结果100%正确，将每个IMF的预测结果进行累加，得到的结果与真实值也会有较大的偏差。这样理解是否正确呢？
   另外，上述过程如果使用EMD分解，只有5%的值偏离10%。

THX

**Comment by allen20200111** [comment]
使用浙江大学的《Improved EEMD-based crude oil price forecasting using LSTM networks》中的方法去预测，其使用了前几个IMF的值作为输入，一阶方差的值进行输出，这样的预测结果时MAPE很小，RMSE和MAPE统计都很完美，但存在明显的滞后性，即不具备预测能力。
![image](https://user-images.githubusercontent.com/37377179/87109166-84602d80-c296-11ea-95a8-796631022118.png)

**Comment by adadadda** [comment]
我也采用EEMD做了测试，将数据分解成多个IMF子序列，然后在累加成一个序列，这样和序列在高频上面有比较大的差距，我怀疑EEMD是否有钝化的能力，减少了高频分量。另外请教一下，看了您的答辩PPT，请问您是将数据先分解再划分测试集和训练集吗？个人感觉这样会利用了未来的信息。还有如果是新加如一个点，就把最后一个点替换掉，请问您是怎么做的验证呢？因为这样如果想验证它的准确度，是十分困难的

**Comment by Corezcy** [comment]
> 我也采用EEMD做了测试，将数据分解成多个IMF子序列，然后在累加成一个序列，这样和序列在高频上面有比较大的差距，我怀疑EEMD是否有钝化的能力，减少了高频分量。另外请教一下，看了您的答辩PPT，请问您是将数据先分解再划分测试集和训练集吗？个人感觉这样会利用了未来的信息。还有如果是新加如一个点，就把最后一个点替换掉，请问您是怎么做的验证呢？因为这样如果想验证它的准确度，是十分困难的

我是先分解，再划分测试集和训练集的。你的这个问题我确实没考虑过。如果先划分测试集和训练集，可能就分解不到那么多的imf了，可以测试一下。不过，大概率imf数量不一致，这个时候就要再验证一下，先划分测试集和训练集再分解最多可以分解多少imf。还有啊，我对EEMD这一块的了解其实也不多，做毕设才学的，大家一块交流交流，不用那么见外。
`如果是新加入一个点，就把最后一个点替换掉`没看懂这句话啥意思。
最后和你再解释一下啊，这是本科毕设做的，我了解的大概率没你那么多，希望多多指点批评

**Comment by adadadda** [comment]
非常感谢你的回复啊，我是一个硕士研究生，也在做这一块的研究。我目前就是这样做的，先划分测试集和训练集然后再分解，这样做必须训练集和测试集的数据长度相等，并且最好只讲训练集的部分数据替换作为测试集，举个例子，可以用7月份的数据做训练，然后用7月前20天数据加8月10天的数据做测试。这样可以得到一个不错的结果，但这样做很难再大量的数据上验证算法。目前这个问题还没有解决

**Comment by Corezcy** [comment]
> 非常感谢你的回复啊，我是一个硕士研究生，也在做这一块的研究。我目前就是这样做的，先划分测试集和训练集然后再分解，这样做必须训练集和测试集的数据长度相等，并且最好只讲训练集的部分数据替换作为测试集，举个例子，可以用7月份的数据做训练，然后用7月前20天数据加8月10天的数据做测试。这样可以得到一个不错的结果，但这样做很难再大量的数据上验证算法。目前这个问题还没有解决

1、`训练集的部分数据替换作为测试集`，没有依据这么做吧，训练集的数据不会和测试集的数据有交集。
2、`训练集和测试集的数据长度相等`，即使数据个数相等，分解出来的imf个数也不一定相等，如果前半部分数据变化大，分解的可能会多；如果后半部分数据比较平滑，分解的可能会少。
3、`这样做很难再大量的数据上验证算法`，`EEMD`分解比较耗时，再加上每个`imf`还要经过`LSTM`得到预测结果，挺费时的；再加上你是人工选取数据，更费力了。
我对这部分的了解也就这么多，希望你找到好的方法，可以留言交流，我也学习学习！
