### ISSUE TITLE
你好，本文所写的论文题目是什么呢论文内容在哪里可以找到，知网上面没有查到

### ISSUE THREAD

**Issue by tiancaixubao** [Corezcy/EEMD-LSTM-DO-Prediction#3]
你好，本文所写的论文题目是什么呢论文内容在哪里可以找到，知网上面没有查到

**Comment by Corezcy** [comment]
> 你好，本文所写的论文题目是什么呢论文内容在哪里可以找到，知网上面没有查到

本科毕设论文不在知网里啊，在单独的本科论文库里，就是看不到的啊
我附带了答辩时候的ppt，你可以参考一下。
ps. 本科毕设水平不高，见谅

**Comment by tiancaixubao** [comment]
非常感谢

**Comment by tiancaixubao** [comment]
你好我的QQ1436911847可以加博主学习几个问题吗

**Comment by tiancaixubao** [comment]
你好你模型里面跑的BP.py是不是实际上还是跑的LSTM的呢

**Comment by Corezcy** [comment]
> 你好你模型里面跑的BP.py是不是实际上还是跑的LSTM的呢，还有在模型里面10,20,30，---90,100这些
> ![image](https://user-images.githubusercontent.com/57984524/108846294-6115a300-7619-11eb-812e-400adceec49a.png)是代表什么参数呢
> 还有一个就是在模型构建里面filepath路径好像没有用到呀
> ![image](https://user-images.githubusercontent.com/57984524/108848437-f5810500-761b-11eb-86ae-b2b1aa3abf48.png)

1.BP.py跑的是BP对照模型啊
https://github.com/Corezcy/EEMD-LSTM-DO-Prediction/blob/master/2-%E6%A8%A1%E5%9E%8B%E9%83%A8%E5%88%86-Model/Code/BP.py#L105

2.10，20，参数，分别代表epochs个数，是不同的模型

3.filepath在训练模型的时候起到保存的作用，后面是调用模型，就没用了
