### ISSUE TITLE
关于EEMD-LSTM-DO-Prediction

### ISSUE THREAD

**Issue by zhangjinrong-byte** [Corezcy/EEMD-LSTM-DO-Prediction#4]
您好，请问能否在知网上搜索到您的论文呢？想参考您的代码做一个水温预测模型，有些地方不太懂，想看一下您的论文。

**Comment by Corezcy** [comment]
> 您好，请问能否在知网上搜索到您的论文呢？想参考您的代码做一个水温预测模型，有些地方不太懂，想看一下您的论文。

搜不到，这是做的本科毕设，不在一个库里边，你要的话我可以私发你，留个邮箱吧
ps.一年后再看，论文里数据异常检测可能是不对的，希望看的时候多加甄别

**Comment by zhangjinrong-byte** [comment]
非常感谢分享，这个是我的邮箱1044835724@qq.com

**Comment by zhangjinrong-byte** [comment]
> > 您好，请问能否在知网上搜索到您的论文呢？想参考您的代码做一个水温预测模型，有些地方不太懂，想看一下您的论文。
> 
> 搜不到，这是做的本科毕设，不在一个库里边，你要的话我可以私发你，留个邮箱吧
> ps.一年后再看，论文里数据异常检测可能是不对的，希望看的时候多加甄别

非常感谢分享，1044835724@qq.com这个是我的邮箱

**Comment by zhangjinrong-byte** [comment]
***@***.***是我的邮箱



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月23日(周三) 中午1:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Corezcy/EEMD-LSTM-DO-Prediction] 关于EEMD-LSTM-DO-Prediction (#4)




  
您好，请问能否在知网上搜索到您的论文呢？想参考您的代码做一个水温预测模型，有些地方不太懂，想看一下您的论文。
  
搜不到，这是做的本科毕设，不在一个库里边，你要的话我可以私发你，留个邮箱吧
 ps.一年后再看，论文里数据异常检测可能是不对的，希望看的时候多加甄别
