### ISSUE TITLE
验证结果出现了问题

### ISSUE THREAD

**Issue by zhangjinrong-byte** [Corezcy/EEMD-LSTM-DO-Prediction#5]
下载了您的代码和数据后，我使用您的数据进行了验证，发现LSTM模型的运行结果和您论文中得到的结论一样，但是EEMD-LSTM模型的运行结果RMSE:0.2370,MAE:0.1733 和您论文中的结果RMSE:0.0211,MAE:0.0143差距较大，查看代码中的模型各参数设置和论文中的设计思路是一样的，并没有发现问题，想请教一下您当时是否遇到这个问题呢？

**Comment by Corezcy** [comment]
> 下载了您的代码和数据后，我使用您的数据进行了验证，发现LSTM模型的运行结果和您论文中得到的结论一样，但是EEMD-LSTM模型的运行结果RMSE:0.2370,MAE:0.1733 和您论文中的结果RMSE:0.0211,MAE:0.0143差距较大，查看代码中的模型各参数设置和论文中的设计思路是一样的，并没有发现问题，想请教一下您当时是否遇到这个问题呢？

没有遇到过，建议你自己重新训练一套EEMD-LSTM模型再试试

**Comment by zhangjinrong-byte** [comment]
好的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月2日(周五) 上午8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Corezcy/EEMD-LSTM-DO-Prediction] 验证结果出现了问题 (#5)




  
下载了您的代码和数据后，我使用您的数据进行了验证，发现LSTM模型的运行结果和您论文中得到的结论一样，但是EEMD-LSTM模型的运行结果RMSE:0.2370,MAE:0.1733 和您论文中的结果RMSE:0.0211,MAE:0.0143差距较大，查看代码中的模型各参数设置和论文中的设计思路是一样的，并没有发现问题，想请教一下您当时是否遇到这个问题呢？
  
没有遇到过，建议你自己重新训练一套EEMD-LSTM模型再试试
