### ISSUE TITLE
你好可以说一下您论文的名字吗，我想下载来看

### ISSUE THREAD

**Issue by study-lmj** [Corezcy/EEMD-LSTM-DO-Prediction#6]

**Comment by Corezcy** [comment]
> 

可以留个邮箱，晚上发给你

**Comment by study-lmj** [comment]
非常感谢，邮箱：&nbsp; ***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Corezcy/EEMD-LSTM-DO-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6)





   
可以留个邮箱，晚上发给你
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Corezcy** [comment]
> 非常感谢，邮箱：&nbsp; ***@***.***
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

看不出你发的啥……

**Comment by study-lmj** [comment]
您好，给你发了张截图，可以看到吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Corezcy/EEMD-LSTM-DO-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6)





  
非常感谢，邮箱：&nbsp; @.***
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
看不出你发的啥……
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Corezcy** [comment]
> 您好，给你发了张截图，可以看到吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上7:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 非常感谢，邮箱：&nbsp; @.*** … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不出你发的啥…… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

看不到

**Comment by study-lmj** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Corezcy/EEMD-LSTM-DO-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 晚上8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6)





  
您好，给你发了张截图，可以看到吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上7:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 非常感谢，邮箱：&nbsp; @.*** … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不出你发的啥…… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
看不到
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Corezcy** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上8:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 您好，给你发了张截图，可以看到吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上7:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 非常感谢，邮箱：&nbsp; @.*** … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不出你发的啥…… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不到 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你可以登录github看看发了什么……

**Comment by study-lmj** [comment]
1016253978@qq.com

**Comment by study-lmj** [comment]
我在github上评论了我的邮箱，看看你那边能看到不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Corezcy/EEMD-LSTM-DO-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上8:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 您好，给你发了张截图，可以看到吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 晚上7:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 非常感谢，邮箱：&nbsp; @.*** … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Corezcy/EEMD-LSTM-DO-Prediction" @.&gt;; 发送时间:&nbsp;2021年9月18日(星期六) 中午11:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6) 可以留个邮箱，晚上发给你 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不出你发的啥…… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 看不到 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你可以登录github看看发了什么……
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Corezcy** [comment]
> https://github.com/Corezcy/EEMD-LSTM-DO-Prediction/blob/a61e38a2df77437c4ec32836708fb75cf97a8d31/4-%E4%BB%85%E4%BE%9B%E5%8F%82%E8%80%83.pdf

已经传上来啦，想看可以拉一下

**Comment by study-lmj** [comment]
感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Corezcy/EEMD-LSTM-DO-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Corezcy/EEMD-LSTM-DO-Prediction] 你好可以说一下您论文的名字吗，我想下载来看 (#6)





  
https://github.com/Corezcy/EEMD-LSTM-DO-Prediction/blob/a61e38a2df77437c4ec32836708fb75cf97a8d31/4-%E4%BB%85%E4%BE%9B%E5%8F%82%E8%80%83.pdf
  
已经传上来啦，想看可以拉一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
