### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by study-lmj** [Corezcy/EEMD-LSTM-DO-Prediction#7]
![1](https://user-images.githubusercontent.com/88019129/136945546-ffbec95b-b591-4c87-8b55-2f7b32651443.png)
![2](https://user-images.githubusercontent.com/88019129/136945561-d8f6f1c0-ccec-41c6-b097-1cfe0900493d.png)
[你好请问一下我运行你代码的时候结果是第一张图，你论文里是第二张图。你论文里的图示正确的，和原始数据一样，但是我运行代码出来的图跟原始数据不一样，但是图形的形状是一样的，只是值不一样，请问你知道问题出在了哪吗，还是说代码少了什么东西或者反归一化的时候出现了问题。

**Comment by Corezcy** [comment]
原因可能：
1、模型选错了
2、反归一化出现问题
3、是不是没有做异常检测、踢值
时间长了，我能想到的也就这些了，你可以对比一下代码哈

**Comment by study-lmj** [comment]
好的谢谢，我看一下
